### ISSUE TITLE
#1 start today with release version 1.0 

### ISSUE THREAD

**Issue by 0riginz** [0riginz/C0ffe1sWh8tWeNeed#1]
We will do this tomorrow at the uni. Please make sure you understand what we have to do.
That means every point from task "Project Infrastructure".

Everbody of us has to understand how KOTLIN, MAVIN/TRAVIS, GIT and JUNIT work!

See you tomorrow

**Comment by nipafx** [comment]
Note I judge participation based on how it shows up on GitHub, so you can't do it all under the same account. Spread the work around. Also note that I'm not available 24/7, so don't start opening PRs like crazy at 1800, expecting me to respond immediately.

**Comment by 0riginz** [comment]
ok.
