### ISSUE TITLE
#1 integrate with Travis

### ISSUE THREAD

**Issue by chris0197** [0riginz/C0ffe1sWh8tWeNeed#12]
@nicolaiparlog

**Comment by nipafx** [comment]
Please ping me again, when the Maven build is set up.

**Comment by chris0197** [comment]
@nicolaiparlog

**Comment by nipafx** [comment]
Pardon my German:

Da dieses Projekt nicht zu einer Organisation gehört, sondern einem User, kann nur der User Travis aktivieren. 😭 Ich kann das nachher konfigurieren, aber anschmeißen muss es @0riginz.

Dazu bitte Schritte 2 und 3 [aus dieser Anleitung](https://docs.travis-ci.com/user/for-beginners) (natürlich für dieses Projekt hier) durchführen und dann wieder hier Bescheid sagen.

**Comment by chris0197** [comment]
@0riginz you have to bring it to run with travis,  because I dont have the rights and i cant change the rights

**Comment by 0riginz** [comment]
![image](https://user-images.githubusercontent.com/30532821/29166079-56191928-7dc5-11e7-8074-544d8e9a7be2.png)

I just flicked the switch. You do nr. 2&3 from the 2nd picture right @nicolaiparlog ?

**Comment by nipafx** [comment]
Yep.
