### ISSUE TITLE
#1 release version 1.0

### ISSUE THREAD

**Issue by chris0197** [0riginz/C0ffe1sWh8tWeNeed#15]

**Comment by nipafx** [comment]
Once all issues in [milestone 1](https://github.com/0riginz/C0ffe1sWh8tWeNeed/milestone/1) are completed, the release can be made as follows (pardon my German):

* `master` auschecken
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, `Edit`, aus dem Tag ein Release machen und die JAR `-with-dependencies` anhängen

![attach-binaries](https://user-images.githubusercontent.com/6537432/28945052-36db7a44-78a5-11e7-843c-892c9de473b8.png)

**Comment by chris0197** [comment]
2.0-SNAPSHOT is running
