### ISSUE TITLE
#1 Activate tests

### ISSUE THREAD

**Issue by nipafx** [0riginz/C0ffe1sWh8tWeNeed#22]
The command `mvn clean install` does not execute tests because the path to test sources is not defined in `pom.xml`. That needs to be fixed.

**Comment by nipafx** [comment]
#24 correctly added the JUnit dependency and `test-compile` execution phase (I missed both of those) but tests are still not executed because `testSourceDirectory` is still not set. So this bug is still open.

**Comment by chris0197** [comment]
The error is fixed the program is running
