### ISSUE TITLE
#1 Use common casing

### ISSUE THREAD

**Issue by nipafx** [0riginz/C0ffe1sWh8tWeNeed#23]
You used upper case letters in a few places, where that is very unusual. Please use lower case here:

* `Main` folder
* `Test` folder
* Folder `FinalProject` (2x)
* Package `FinalProject`

In Windows, it can be hard to rename from upper to lower case because it doesn't care about the difference. It might be necessary to rename folder `Foo` to `FooX`, and then to `foo`.

**Comment by chris0197** [comment]
@nicolaiparlog  at git i cant push the changes 

Locally I changed the names.

**Comment by nipafx** [comment]
Why can't you push the changes? Please paste the output of `git remote -vv`, `git branch -a`, and `git status` (text, not images!), so I can help you solve that.

**Comment by chris0197** [comment]
The error is fixed the program is running
