### ISSUE TITLE
#1 Create issues

### ISSUE THREAD

**Issue by nipafx** [0riginz/C0ffe1sWh8tWeNeed#7]
Please make sure to create all issues for one block before starting to work on it. Also, remember to assign them to the corresponding milestone.

**Comment by nipafx** [comment]
Also two general comments:

* Even if you edit files on GitHub, please create a pull request for them.
* Wait with merging pull requests until I've given a thumbs-up (or didn#t react to changes for some hours).

**Comment by 0riginz** [comment]
Does it mean we should start an Issue for every task like:
-create a README.md
-add a license 
-etc.

... write something to each and close it, if there are no questions anymore?

**Comment by nipafx** [comment]
In general, yes, you should have an issue for each of the tasks I created. But to save you some time, you don't have to create them for tasks you've already completed. There are still a number of tasks in Block 1 that you haven't completed, though, and I'd like you to create issues for them.

**Comment by 0riginz** [comment]
ok

**Comment by nipafx** [comment]
I'll leave this open until you've actually created the issues...
